[package]
name = "kim_synth"
version = "0.1.0"
authors = ["Sam Kim <skim13@cs.stanford.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8"
error-chain = "0.12.0"
rand = "0.4"
time = "0.1.40"
